# Random Forests Algorithm Adaptation

In [1]:
import pandas as pd
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.metrics import hamming_loss
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
full_data = pd.DataFrame(pd.read_pickle('combined_imdb_tmdb_data.picke'))
full_data.head()

,adult,backdrop_path,belongs_to_collection,budget,cast,certificates,color info,countries,director,genres,homepage,id,imdb_id,languages,mpaa,original_language,original_title,overview,plot,popularity,poster_path,production companies,production_companies,production_countries,rating,release_date,revenue,runtime,runtimes,spoken_languages,status,tagline,title,video,vote_average,vote_count,votes,writer,year
0,False,/nhhV4jSDZcBCZuOjkbPUAGa8EKG.jpg,None,0,"[Alexander Ludwig, Christopher Eccleston, Ian ...","[Argentina:13, Australia:PG, Brazil:Livre, Can...",[Color],[USA],[David L. Cunningham],"[{u'id': 12, u'name': u'Adventure'}, {u'id': 1...",,2274,tt0484562,[English],Rated PG for fantasy action and some scary images,en,The Seeker: The Dark Is Rising,A boy's life is turned upside down when he lea...,"[The film tells the story of Will Stanton, a y...",0.610288,/wmPHQxchlpuRAFG94NWMtCZF65k.jpg,"[Twentieth Century Fox Film Corporation, Walde...",[{u'name': u'Twentieth Century Fox Film Corpor...,"[{u'iso_3166_1': u'US', u'name': u'United Stat...",4.8,2007-10-05,0,94.0,[99],"[{u'iso_639_1': u'en', u'name': u'English'}]",Released,,The Seeker: The Dark Is Rising,False,4.8,88,13504.0,"[John Hodge, Susan Cooper]",2007.0
1,False,/d23XXntJrVwNENvdriJdqlW1ae6.jpg,None,3000000,"[William Holden, Alec Guinness, Jack Hawkins, ...","[Argentina:13, Australia:PG, Australia:G::(Ori...",[Color::(Technicolor)],"[UK, USA]",[David Lean],"[{u'id': 18, u'name': u'Drama'}, {u'id': 36, u...",,826,tt0050212,"[English, Japanese, Thai]",Rated PG for mild war violence (re-rating) (1991),en,The Bridge on the River Kwai,The classic story of English POWs in Burma for...,[The film deals with the situation of British ...,1.138653,/vtPR6tSHeu35rF6qTDw3Yjr9eDg.jpg,"[Columbia Pictures Corporation, Horizon Pictur...","[{u'name': u'Columbia Pictures Corporation', u...","[{u'iso_3166_1': u'GB', u'name': u'United King...",8.2,1957-10-02,33300000,161.0,[161],"[{u'iso_639_1': u'ja', u'name': u'日本語'}, {u'is...",Released,It spans a whole new world of entertainment!,The Bridge on the River Kwai,False,7.6,450,159094.0,"[Pierre Boulle, Carl Foreman, Michael Wilson]",1957.0
2,False,/2Kx2q1GOmYRjxmILEFIusMIGTUc.jpg,"{u'id': 123800, u'poster_path': u'/giaxAC74fht...",2700000,"[Ethan Hawke, Julie Delpy, Vernon Dobtcheff, L...","[Argentina:Atp, Australia:M, Austria:0, Brazil...",[Color],[USA],[Richard Linklater],"[{u'id': 18, u'name': u'Drama'}, {u'id': 10749...",http://www.warnerbros.com/?site=beforesunset#/...,80,tt0381681,"[English, French]",Rated R for language and sexual references (Ap...,en,Before Sunset,Nine years ago two strangers met by chance and...,[Early thirty-something American Jesse Wallace...,1.026352,/cIj6yWJKUjdCCO7vuZQKl0NqCQe.jpg,"[Warner Independent Pictures (WIP), Castle Roc...","[{u'name': u'Castle Rock Entertainment', u'id'...","[{u'iso_3166_1': u'US', u'name': u'United Stat...",8.0,2004-02-10,15992615,80.0,[80],"[{u'iso_639_1': u'en', u'name': u'English'}, {...",Released,What if you had a second chance with the one t...,Before Sunset,False,7.6,580,177647.0,"[Richard Linklater, Julie Delpy, Ethan Hawke, ...",2004.0
3,False,/Dmcv6XpQ9h8AoRIEhD1hayNpd8.jpg,None,0,"[Michael Bolton, Sarah Shahi, Adam Scott, Matt...","[Singapore:NC16, South Korea:18, USA:TV-MA]",[Color],[USA],"[Scott Aukerman, Akiva Schaffer]","[{u'id': 35, u'name': u'Comedy'}, {u'id': 1040...",,430780,tt6343706,[English],NaN,en,"Michael Bolton's Big, Sexy Valentine's Day Spe...",After Santa tells Michael Bolton that he needs...,[After Santa tells Michael Bolton that he need...,0.097190,/fomxGvTf5HBtaupI9Rk4UGg43OB.jpg,"[Comedy Bang! Bang! Productions, Netflix, Pass...","[{u'name': u'Netflix', u'id': 59811}]","[{u'iso_3166_1': u'US', u'name': u'United Stat...",NaN,2017-02-07,0,54.0,[USA:54],"[{u'iso_639_1': u'en', u'name': u'English'}]",Released,,"Michael Bolton's Big, Sexy Valentine's Day Spe...",False,8.0,4,NaN,"[Scott Aukerman, David Ferguson, Mike Hanford,...",2017.0
4,False,/8fYXNzpwjJIUmP6ZtxPO3zpIXJa.jpg,None,15000000,"[Richard E. Grant, Catherine O'Hara, Nick Prid...","[Argentina:Atp, Australia:PG, Canada:PG::(Onta...",[Color],"[UK, USA]",[Mark Palansky],"[{u'id': 14, u'name': u'Fantasy'}, {u'id': 35,...",http://www.penelopethemovie.com/,7985,tt0472160,[English],"Rated PG for thematic elements, some innuendo ...",en,Penelope,"Forlorn heiress Penelope Wilhern is cursed, an...","[In this modern-day romantic tale, Penelope is...",1.222510,/f1onDDba0W85o2eIZr4vcfqI47j.jpg,"[Summit Entertainment, Stone Village Pictures,...","[{u'name': u'Tatira-Hiller Productions', u'id'...","[{u'iso_3166_1': u'GB', u'name': u'United King...",6.8,2006-03-01,0,103.0,"[104, Thailand:86::(DVD)]","[{u'iso_639_1': u'en', u'name': u'English'}]",Released,A fairytale like no other.,Penelope,False,6.5,317,52587.0,[Leslie Caveny],2006.0

In [4]:
cols_to_save = ["budget", "adult", "director", "genres", "id", "original_language", "popularity", 
                "rating", "revenue", "runtime", "vote_average", "vote_count", "votes", "writer", "year"]

In [5]:
full_data_condensed = full_data[cols_to_save]

In [50]:
train_test_indices = pd.read_pickle('train_val_test_byid.pkl')

In [52]:
train_test_indices["train"]

[252178,
 430364,
 214775,
 362886,
 19913,
 176068,
 8420,
 17443,
 294087,
 14062,
 449334,
 333371,
 451406,
 4951,
 95864,
 14098,
 16123,
 37308,
 13654,
 11674,
 36130,
 51248,
 347938,
 9282,
 389,
 81393,
 42556,
 169853,
 17134,
 76203,
 10821,
 44115,
 449929,
 58857,
 13436,
 10096,
 300671,
 319337,
 450982,
 18200,
 407806,
 3021,
 1492,
 2749,
 52256,
 16996,
 14902,
 381630,
 403357,
 76349,
 332286,
 388904,
 321303,
 47817,
 428741,
 61755,
 203575,
 425849,
 1845,
 9401,
 136400,
 391975,
 86703,
 246400,
 173,
 16266,
 14161,
 213308,
 844,
 25114,
 470,
 64688,
 8065,
 37645,
 187017,
 271234,
 13989,
 1429,
 6557,
 170,
 32716,
 20453,
 40508,
 16314,
 320349,
 1280,
 30762,
 14168,
 5176,
 4513,
 62206,
 166666,
 284564,
 82666,
 44877,
 86820,
 38680,
 403119,
 64686,
 44662,
 376575,
 13365,
 21735,
 362046,
 4993,
 38142,
 40807,
 411500,
 172767,
 3682,
 27759,
 76360,
 29776,
 20536,
 84577,
 65194,
 51200,
 449652,
 359749,
 43254,
 65,
 1958,
 79997,
 3489,
 7295,
 8224,
 27,
 12244,
 14097,
 19929,
 8329,
 10664,
 80280,
 453,
 374316,
 18305,
 41244,
 324807,
 325078,
 4917,
 5902,
 1358,
 13923,
 1607,
 9487,
 37316,
 44867,
 174316,
 13187,
 30421,
 13345,
 1816,
 13189,
 16716,
 17979,
 348634,
 311093,
 81332,
 366018,
 369061,
 8892,
 423893,
 369060,
 42559,
 407655,
 74018,
 532,
 100788,
 36848,
 348668,
 379514,
 13358,
 69472,
 261458,
 381289,
 41206,
 441533,
 421761,
 32075,
 22649,
 80255,
 881,
 110808,
 179111,
 58772,
 428849,
 623,
 391,
 6399,
 17768,
 56415,
 10915,
 323384,
 47964,
 9726,
 15789,
 530,
 374460,
 53197,
 8194,
 71654,
 253041,
 43306,
 704,
 269494,
 139038,
 421760,
 59,
 270010,
 37108,
 305943,
 31696,
 11287,
 251471,
 45578,
 8067,
 45156,
 283227,
 8976,
 19946,
 56514,
 219302,
 14676,
 70387,
 15244,
 874,
 45227,
 28162,
 14447,
 286532,
 23908,
 10210,
 19075,
 8288,
 449776,
 13370,
 188161,
 77459,
 241239,
 157849,
 13247,
 10971,
 10072,
 10131,
 10160,
 10014,
 23437,
 377,
 15927,
 321751,
 1965,
 9559,
 25673,
 9526,
 258665,
 369057,
 79113,
 21575,
 41780,
 29478,
 413308,
 61237,
 258691,
 11257,
 88273,
 299582,
 435107,
 3509,
 73861,
 31056,
 42563,
 1594,
 378064,
 159932,
 26522,
 42229,
 19610,
 404378,
 42384,
 4701,
 4552,
 95536,
 437068,
 359187,
 4949,
 1645,
 16524,
 65674,
 775,
 35614,
 49953,
 113594,
 347026,
 55465,
 2841,
 238749,
 364067,
 707,
 169917,
 232572,
 10229,
 348674,
 410314,
 263950,
 28974,
 644,
 327309,
 43642,
 14336,
 52090,
 22349,
 18169,
 122906,
 72331,
 430616,
 19429,
 74777,
 42017,
 66,
 86828,
 9788,
 451740,
 11874,
 3049,
 139971,
 21469,
 18790,
 4688,
 34269,
 75674,
 32850,
 23051,
 87208,
 18516,
 1023,
 22051,
 2757,
 11508,
 2058,
 369533,
 371627,
 79931,
 13506,
 277154,
 250880,
 308457,
 360606,
 341043,
 59803,
 1404,
 2973,
 319993,
 14766,
 13794,
 62931,
 14711,
 217667,
 82700,
 440249,
 109520,
 10589,
 118612,
 188839,
 16091,
 123103,
 1782,
 15039,
 302828,
 31619,
 192813,
 59883,
 186971,
 24930,
 24932,
 17047,
 24735,
 26428,
 2000,
 84169,
 44920,
 37088,
 2211,
 20737,
 9973,
 9772,
 145316,
 284674,
 13595,
 375290,
 813,
 22315,
 109824,
 51249,
 132894,
 11238,
 812,
 150066,
 329892,
 60542,
 325242,
 33065,
 10235,
 42668,
 43839,
 1966,
 25032,
 17479,
 73672,
 8489,
 398929,
 12092,
 23761,
 15162,
 241259,
 34461,
 18917,
 19279,
 30936,
 312526,
 13954,
 98387,
 348,
 8078,
 20856,
 22559,
 440,
 8077,
 381020,
 7305,
 705,
 90241,
 276087,
 210908,
 402529,
 10914,
 152747,
 10631,
 317121,
 10912,
 143,
 49046,
 15922,
 56590,
 43316,
 39936,
 16858,
 9022,
 891,
 21355,
 18172,
 289095,
 347123,
 133715,
 376386,
 27098,
 377428,
 37036,
 43825,
 262504,
 369885,
 302348,
 786,
 24615,
 222936,
 12142,
 2043,
 72163,
 5966,
 43562,
 227425,
 258096,
 12819,
 264274,
 8072,
 221417,
 314065,
 11542,
 14458,
 6477,
 55301,
 258509,
 23398,
 26622,
 120890,
 11352,
 186024,
 393775,
 279,
 147703,
 16049,
 13796,
 214418,
 252328,
 126891,
 49320,
 9045,
 11467,
 40196,
 40852,
 14,
 9310,
 4982,
 838,
 16018,
 250066,
 73,
 340485,
 445068,
 14242,
 25678,
 13496,
 8277,
 26123,
 8275,
 2105,
 24587,
 29204,
 71552,
 190859,
 17073,
 75049,
 261392,
 8273,
 18116,
 46105,
 72913,
 11831,
 27214,
 203835,
 414016,
 125558,
 55,
 263057,
 13803,
 331781,
 222267,
 8356,
 10008,
 2769,
 27653,
 4978,
 10380,
 31473,
 814,
 451793,
 114048,
 24684,
 14348,
 294861,
 15653,
 1781,
 357432,
 29185,
 18174,
 59435,
 2623,
 81949,
 14863,
 9360,
 19543,
 9535,
 9444,
 93,
 1698,
 109443,
 253235,
 33107,
 253639,
 4886,
 54072,
 21038,
 21352,
 895,
 202471,
 22356,
 635,
 363484,
 15916,
 11227,
 22183,
 44446,
 44450,
 13448,
 24019,
 270632,
 57210,
 9506,
 12689,
 315064,
 44629,
 50135,
 22191,
 48891,
 1439,
 96724,
 13664,
 250546,
 396422,
 51352,
 21485,
 22522,
 81416,
 25209,
 703,
 43887,
 15739,
 196867,
 26177,
 268122,
 291270,
 11595,
 36136,
 55420,
 146117,
 201132,
 11604,
 351339,
 17609,
 445758,
 125490,
 74349,
 233748,
 8916,
 18094,
 9563,
 379990,
 56623,
 73896,
 3685,
 155685,
 187146,
 85848,
 130964,
 43329,
 164337,
 28,
 79765,
 1579,
 568,
 50357,
 231504,
 377431,
 269650,
 11633,
 45295,
 13981,
 4281,
 328429,
 332179,
 340357,
 24913,
 297802,
 65584,
 14191,
 18098,
 60488,
 125745,
 31446,
 4658,
 300900,
 10172,
 11637,
 209244,
 92393,
 198993,
 71254,
 415132,
 25832,
 2,
 22679,
 11044,
 132939,
 1073,
 37828,
 95,
 4597,
 10975,
 30432,
 15383,
 13522,
 329257,
 10204,
 178862,
 410199,
 247620,
 329865,
 138486,
 360799,
 61049,
 42949,
 9992,
 51052,
 256274,
 2898,
 283489,
 312497,
 266568,
 330112,
 5055,
 20110,
 271185,
 121856,
 26920,
 18176,
 291549,
 17814,
 14044,
 9564,
 9929,
 11625,
 9642,
 2395,
 9369,
 9318,
 11047,
 170522,
 273756,
 16577,
 243145,
 181656,
 13715,
 15556,
 140062,
 22553,
 80631,
 181118,
 15466,
 8965,
 10865,
 199933,
 89691,
 407624,
 30922,
 188924,
 4347,
 340382,
 295830,
 59678,
 32087,
 247426,
 18976,
 1786,
 11075,
 376228,
 43352,
 152737,
 225086,
 156711,
 818,
 816,
 817,
 6972,
 262543,
 16921,
 12761,
 50479,
 10881,
 451581,
 76600,
 83533,
 19995,
 111332,
 99861,
 299536,
 63374,
 450248,
 395,
 449748,
 19255,
 420276,
 5890,
 19026,
 64124,
 47831,
 26837,
 318042,
 24884,
 137127,
 256040,
 9598,
 9447,
 1164,
 32610,
 26984,
 56499,
 339403,
 31117,
 22345,
 11212,
 10942,
 15289,
 10921,
 394132,
 450794,
 60086,
 326923,
 100600,
 330127,
 19096,
 26477,
 165,
 196,
 12635,
 228973,
 2924,
 62648,
 332704,
 19241,
 451662,
 255268,
 8961,
 13633,
 9737,
 355066,
 3132,
 31591,
 14554,
 11853,
 273641,
 208134,
 258805,
 138372,
 12143,
 172828,
 376659,
 338964,
 3133,
 38807,
 3134,
 118957,
 362045,
 233805,
 46592,
 20497,
 138178,
 9750,
 312266,
 25913,
 21032,
 3170,
 80207,
 331214,
 333675,
 1969,
 44022,
 23367,
 39907,
 13184,
 207769,
 213386,
 14002,
 8069,
 45559,
 417047,
 361380,
 15906,
 23566,
 15015,
 13283,
 15165,
 21705,
 13459,
 91342,
 34134,
 316322,
 13002,
 15167,
 168903,
 18198,
 16418,
 57737,
 44874,
 77499,
 196254,
 377897,
 434757,
 215828,
 242042,
 248574,
 359440,
 9907,
 32142,
 3175,
 19594,
 290,
 139126,
 3093,
 402,
 334394,
 271715,
 549,
 179109,
 62678,
 333669,
 14911,
 43546,
 15208,
 415,
 16234,
 414,
 364,
 29751,
 449390,
 209112,
 321528,
 2661,
 268,
 242643,
 366924,
 13851,
 14919,
 21683,
 411736,
 142061,
 382322,
 40662,
 69735,
 11548,
 17189,
 91245,
 16873,
 1705,
 46874,
 11463,
 59197,
 434753,
 57709,
 13524,
 14808,
 109417,
 207909,
 3176,
 44943,
 5491,
 65881,
 31623,
 643,
 44833,
 325553,
 257368,
 69315,
 328255,
 242546,
 339846,
 4551,
 37416,
 39519,
 15592,
 62753,
 1281,
 38117,
 283587,
 84175,
 17667,
 66767,
 70342,
 250477,
 36851,
 15048,
 29483,
 61416,
 80788,
 21033,
 10020,
 30844,
 321612,
 49038,
 13313,
 90603,
 46554,
 17880,
 15421,
 354100,
 2977,
 379998,
 1636,
 10202,
 62489,
 5559,
 65769,
 24478,
 11806,
 4011,
 397837,
 204922,
 301804,
 132344,
 76,
 80,
 7972,
 410718,
 19155,
 283350,
 48281,
 198277,
 55347,
 413548,
 14028,
 8007,
 10961,
 ...]

In [7]:
genres = full_data_condensed["genres"]

In [8]:
genre_ids = []
for genre_list in genres:
    genre_ids.append([genre["name"] for genre in genre_list])

In [9]:
full_data_condensed["genres"] = genre_ids

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [10]:
genre_names = []
for genre_sublist in genre_ids:
    genre_names += genre_sublist
genre_names = list(set(genre_names))

In [11]:
genre_names

[u'Mystery',
 u'Romance',
 u'Crime',
 u'Family',
 u'Science Fiction',
 u'Horror',
 u'Foreign',
 u'Drama',
 u'Fantasy',
 u'Western',
 u'Animation',
 u'Music',
 u'Adventure',
 u'Action',
 u'TV Movie',
 u'Comedy',
 u'Documentary',
 u'War',
 u'Thriller',
 u'History']

In [12]:
for genre in genre_names:
    full_data_condensed[genre] = [int(genre in genre_list) for genre_list in full_data_condensed["genres"]]

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [13]:
import numpy as np

In [14]:
np.sum(full_data_condensed["Mystery"])

1172

In [16]:
full_data_condensed.head()

,budget,adult,director,genres,id,original_language,popularity,rating,revenue,runtime,vote_average,vote_count,votes,writer,year,Mystery,Romance,Crime,Family,Science Fiction,Horror,Foreign,Drama,Fantasy,Western,Animation,Music,Adventure,Action,TV Movie,Comedy,Documentary,War,Thriller,History
0,0,False,[David L. Cunningham],"[Adventure, Drama, Fantasy, Family, Thriller]",2274,en,0.610288,4.8,0,94.0,4.8,88,13504.0,"[John Hodge, Susan Cooper]",2007.0,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0
1,3000000,False,[David Lean],"[Drama, History, War]",826,en,1.138653,8.2,33300000,161.0,7.6,450,159094.0,"[Pierre Boulle, Carl Foreman, Michael Wilson]",1957.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
2,2700000,False,[Richard Linklater],"[Drama, Romance]",80,en,1.026352,8.0,15992615,80.0,7.6,580,177647.0,"[Richard Linklater, Julie Delpy, Ethan Hawke, ...",2004.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,False,"[Scott Aukerman, Akiva Schaffer]","[Comedy, Music]",430780,en,0.097190,NaN,0,54.0,8.0,4,NaN,"[Scott Aukerman, David Ferguson, Mike Hanford,...",2017.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,15000000,False,[Mark Palansky],"[Fantasy, Comedy, Romance]",7985,en,1.222510,6.8,0,103.0,6.5,317,52587.0,[Leslie Caveny],2006.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0

In [28]:
first_writers = []
for writer_list in full_data_condensed["writer"]:
    if type(writer_list) == list:
        first_writers.append(writer_list[0])
    else:
        first_writers.append(np.nan)

In [30]:
len(list(set(first_writers)))

7486

In [35]:
for column in ["director", "genres", "writer"]:
    full_data_condensed.drop(column, axis=1, inplace=True)

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [36]:
full_data_condensed.head()

,budget,adult,id,original_language,popularity,rating,revenue,runtime,vote_average,vote_count,votes,year,Mystery,Romance,Crime,Family,Science Fiction,Horror,Foreign,Drama,Fantasy,Western,Animation,Music,Adventure,Action,TV Movie,Comedy,Documentary,War,Thriller,History
0,0,False,2274,en,0.610288,4.8,0,94.0,4.8,88,13504.0,2007.0,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0
1,3000000,False,826,en,1.138653,8.2,33300000,161.0,7.6,450,159094.0,1957.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
2,2700000,False,80,en,1.026352,8.0,15992615,80.0,7.6,580,177647.0,2004.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,False,430780,en,0.097190,NaN,0,54.0,8.0,4,NaN,2017.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,15000000,False,7985,en,1.222510,6.8,0,103.0,6.5,317,52587.0,2006.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0

In [38]:
full_data_condensed.drop("original_language", axis=1, inplace=True)

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [44]:
full_data_condensed["adult"] = [int(adult) for adult in full_data_condensed["adult"]]

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [48]:
full_data_condense

,budget,id,popularity,rating,revenue,runtime,vote_average,vote_count,votes,year,Mystery,Romance,Crime,Family,Science Fiction,Horror,Foreign,Drama,Fantasy,Western,Animation,Music,Adventure,Action,TV Movie,Comedy,Documentary,War,Thriller,History
0,0,2274,0.610288,4.8,0,94.0,4.8,88,13504.0,2007.0,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0
1,3000000,826,1.138653,8.2,33300000,161.0,7.6,450,159094.0,1957.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
2,2700000,80,1.026352,8.0,15992615,80.0,7.6,580,177647.0,2004.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,430780,0.097190,NaN,0,54.0,8.0,4,NaN,2017.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,15000000,7985,1.222510,6.8,0,103.0,6.5,317,52587.0,2006.0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
5,4500000,53157,0.132750,6.2,0,102.0,5.0,14,1425.0,1985.0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0
6,0,43821,0.064609,6.7,0,92.0,6.2,10,2197.0,1940.0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0
7,0,3686,0.459007,6.6,0,94.0,6.5,25,2274.0,1964.0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
8,0,13675,0.205311,7.4,0,25.0,6.8,61,10445.0,1969.0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0
9,0,20617,0.021047,6.9,0,100.0,6.5,16,6220.0,1999.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1
10,0,373451,0.073297,7.4,0,110.0,7.1,26,1362.0,2016.0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
11,0,70027,0.196649,7.6,0,101.0,7.0,21,1850.0,2008.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12,0,196254,0.455040,6.0,0,75.0,6.0,24,504.0,2013.0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0
13,0,60646,0.050744,6.7,0,100.0,5.6,7,1082.0,1948.0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0
14,250000,28136,0.008971,7.0,0,75.0,7.7,5,263.0,2009.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
15,0,351964,0.664777,6.0,0,88.0,5.9,80,6749.0,2016.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
16,0,86493,0.702882,4.3,0,95.0,4.7,8,357.0,1973.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
17,0,99438,0.168024,5.8,0,99.0,5.0,4,361.0,1974.0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
18,18000000,253235,1.440436,5.8,25312387,94.0,5.7,137,9809.0,2014.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
19,15000000,271674,1.477510,6.9,9104716,107.0,7.0,212,13454.0,2014.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
20,0,15289,0.563465,6.5,0,75.0,6.4,24,3431.0,2007.0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
21,32000000,11637,0.893943,4.6,97918663,95.0,5.2,181,23783.0,2005.0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
22,0,152581,0.982741,7.5,0,25.0,6.3,24,2142.0,2012.0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
23,4000000,1809,0.925847,6.7,0,110.0,6.2,143,45358.0,2002.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
24,0,144113,0.002086,6.6,0,40.0,5.5,2,226.0,2006.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
25,0,30983,0.164396,8.8,0,720.0,8.2,22,8355.0,1998.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
26,0,127533,1.050186,7.6,61700000,134.0,7.1,144,15949.0,2012.0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
27,0,19237,0.514312,5.5,0,82.0,5.8,26,6053.0,2009.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
28,8700000,3509,1.625370,7.1,7659918,100.0,6.8,439,92639.0,2006.0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
29,0,378779,0.937371,8.2,0,379.0,8.2,38,12289.0,2016.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12211,0,35648,0.340712,6.9,0,79.0,5.6,5,1483.0,1991.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
12212,35000000,271718,6.290461,6.3,140795793,125.0,5.9,1010,105215.0,2015.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
12213,0,442438,0.185540,NaN,0,90.0,5.0,1,NaN,2017.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
12214,80000000,50546,3.098945,6.4,214918407,117.0,6.3,1272,181054.0,2011.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
12215,2627000,43306,0.224095,7.0,5363000,120.0,5.4,7,1696.0,1943.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0
12216,0,16138,0.204771,6.4,0,107.0,6.4,30,4397.0,2004.0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1
12217,0,21501,0.336305,7.0,0,83.0,7.4,18,2606.0,2007.0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
12218,7,440642,1.565732,NaN,0,140.0,10.0,1,NaN,2017.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
12219,0,188839,1.889269,4.7,0,92.0,4.3,18,1256.0,2015.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
12220,0,452126,0.042695,6.2,0,NaN,6.0,1,8.0,2010.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12221,0,46992,0.228664,7.4,0,121.0,6.3,21,8866.0,1998.0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
12222,4000000,158150,0.038892,6.3,0,0.0,4.6,16,2176.0,2012.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0
12223,0,258665,0.338287,7.3,0,103.0,5.9,10,1656.0,2014.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
12224,0,19727,1.835127,4.4,0,95.0,4.6,16,3505.0,2009.0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0
12225,0,363486,0.268574,6.7,0,84.0,6.5,14,916.0,2015.0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0
12226,0,10652,1.108808,6.7,13839404,112.0,6.5,94,19732.0,1987.0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
12227,1500000,414190,3.102148,6.0,0,90.0,6.0,167,8331.0,2017.0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
12228,16000000,9689,1.074950,6.6,0,112.0,6.3,91,22516.0,2002.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
12229,0,415086,0.105382,9.2,0,97.0,7.5,2,271.0,2017.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
12230,23000000,35614,0.655392,5.3,71368,76.0,4.1,30,4724.0,1994.0,0,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0
12231,0,334537,1.335974,5.8,0,92.0,8.0,3,77.0,2017.0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
12232,0,16123,0.538027,2.4,0,85.0,2.8,21,3932.0,2008.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12233,0,25752,0.487175,3.7,0,82.0,3.4,24,3288.0,1999.0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12234,8200000,1788,2.461898,6.5,80035402,107.0,6.2,399,54949.0,1984.0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
12235,0,25599,0.939708,7.7,0,64.0,7.1,30,6031.0,1937.0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0
12236,15000000,64502,0.598997,5.7,0,178.0,5.5,29,3423.0,2009.0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
12237,4000000,257087,1.876711,4.7,0,93.0,4.5,88,5173.0,2016.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12238,0,59197,1.144161,1.9,0,91.0,3.9,39,4425.0,2011.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
12239,0,451884,0.006893,5.0,0,54.0,0.0,0,12.0,1945.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
12240,110000000,787,3.973688,6.5,478207520,120.0,6.5,2225,368348.0,2005.0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,1,0

In [47]:
full_data_condensed.drop("adult", axis=1, inplace=True)

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [53]:
df_train = full_data_condensed[full_data_condensed["id"] in train_test_indices["train"]]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [57]:
train_rows = [tmdb_id in train_test_indices["train"] for tmdb_id in full_data_condensed["id"]]
test_rows = [tmdb_id in train_test_indices["validation"] for tmdb_id in full_data_condensed["id"]]

In [58]:
df_train = full_data_condensed[train_rows]
df_test = full_data_condensed[test_rows]

In [59]:
df_train.to_csv("full_data_train.csv")
df_test.to_csv("full_data_test.csv")

In [56]:
train_test_indices.keys()

['test', 'train', 'validation']

In [113]:
imdb5k = pd.read_pickle('imdb5000onehot.pkl')
imdb5k.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,actor_1_name,...,i_Drama,i_Action,i_Documentary,i_Musical,i_History,i_Family,i_Fantasy,i_Game-Show,i_Sport,i_Biography
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,CCH Pounder,...,0,1,0,0,0,0,1,0,0,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Johnny Depp,...,0,1,0,0,0,0,1,0,0,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Christoph Waltz,...,0,1,0,0,0,0,0,0,0,0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Tom Hardy,...,0,1,0,0,0,0,0,0,0,0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Doug Walker,...,0,0,1,0,0,0,0,0,0,0

In [114]:
imdb5k.columns

Index([u'color', u'director_name', u'num_critic_for_reviews', u'duration',
       u'director_facebook_likes', u'actor_3_facebook_likes', u'actor_2_name',
       u'actor_1_facebook_likes', u'gross', u'actor_1_name', u'movie_title',
       u'num_voted_users', u'cast_total_facebook_likes', u'actor_3_name',
       u'facenumber_in_poster', u'plot_keywords', u'movie_imdb_link',
       u'num_user_for_reviews', u'language', u'country', u'content_rating',
       u'budget', u'title_year', u'actor_2_facebook_likes', u'imdb_score',
       u'aspect_ratio', u'movie_facebook_likes', u'i_Sci-Fi', u'i_Crime',
       u'i_Romance', u'i_Animation', u'i_Music', u'i_Comedy', u'i_War',
       u'i_Horror', u'i_Film-Noir', u'i_Adventure', u'i_News', u'i_Reality-TV',
       u'i_Thriller', u'i_Western', u'i_Mystery', u'i_Short', u'i_Drama',
       u'i_Action', u'i_Documentary', u'i_Musical', u'i_History', u'i_Family',
       u'i_Fantasy', u'i_Game-Show', u'i_Sport', u'i_Biography'],
      dtype='object')

In [115]:
# print categoricals
for col in imdb5k.columns:
    if imdb5k[col].dtype == 'object':
        print col

color
director_name
actor_2_name
actor_1_name
movie_title
actor_3_name
plot_keywords
movie_imdb_link
language
country
content_rating

In [116]:
imdb5k['plot_keywords'].head()

0               avatar|future|marine|native|paraplegic
1    goddess|marriage ceremony|marriage proposal|pi...
2                  bomb|espionage|sequel|spy|terrorist
3    deception|imprisonment|lawlessness|police offi...
4                                                  NaN
Name: plot_keywords, dtype: object

In [117]:
# one-hot encode select categoricals
# good_categories = ['color', 'country', 'content_rating']
good_categories = []
imdb_quant = pd.DataFrame()
for col in imdb5k.columns:
    if imdb5k[col].dtype != 'object':
        imdb_quant[col] = imdb5k[col]
    elif col in good_categories:
        imdb_quant = pd.concat([imdb_quant, pd.get_dummies(imdb5k[col])], axis=1)

In [ ]:
# x y split
imdb5k_X = imdb_quant.ix[:,0:list(imdb_quant.columns).index('i_Sci-Fi')]
imdb5k_Y = imdb_quant.ix[:,list(imdb_quant.columns).index('i_Sci-Fi'):len(imdb_quant.columns)]

# impute
def impute(dataf):
    for col in dataf.columns:
        dataf[col].fillna(dataf[col].mean(), inplace=True)
impute(imdb5k_X)
impute(imdb5k_Y)

# train test split
x_train, x_test, y_train, y_test = train_test_split(imdb5k_X, imdb5k_Y, stratify = imdb5k_Y)

In [119]:
params = {
    'n_estimators': [100],
    'max_features': ['auto', 'log2', None, 1] + range(5, 20, 5),
    'n_jobs' : [-1]
}

CV_rf = GridSearchCV(RandomForestClassifier(), param_grid=params, cv=5, n_jobs=-1)
CV_rf.fit(x_train, y_train)
print CV_rf.best_params_
print CV_rf.best_score_
print CV_rf.score(x_test, y_test)

{'max_features': None, 'n_estimators': 100, 'n_jobs': -1}
0.486515071391
0.584456780333

In [120]:
hamming_loss(y_test, CV_rf.predict(x_test))

0.04221313975477338

In [122]:
pd.DataFrame({'feature': x_train.columns, 'importance': CV_rf.best_estimator_.feature_importances_})

                      feature  importance
0      num_critic_for_reviews    0.066859
1                    duration    0.107029
2     director_facebook_likes    0.056514
3      actor_3_facebook_likes    0.054535
4      actor_1_facebook_likes    0.048569
5                       gross    0.074388
6             num_voted_users    0.069728
7   cast_total_facebook_likes    0.049365
8        facenumber_in_poster    0.035870
9        num_user_for_reviews    0.067889
10                     budget    0.107803
11                 title_year    0.069676
12     actor_2_facebook_likes    0.049389
13                 imdb_score    0.078701
14               aspect_ratio    0.026620
15       movie_facebook_likes    0.037065

In [ ]:
# x y split
imdb5k_X = imdb_quant.ix[:,0:list(imdb_quant.columns).index('i_Sci-Fi')]
imdb5k_Y = imdb_quant.ix[:,list(imdb_quant.columns).index('i_Sci-Fi'):len(imdb_quant.columns)]

# impute
def impute(dataf):
    for col in dataf.columns:
        dataf[col].fillna(dataf[col].mean(), inplace=True)
impute(imdb5k_X)
impute(imdb5k_Y)

# train test split
x_train, x_test, y_train, y_test = train_test_split(imdb5k_X, imdb5k_Y, stratify = imdb5k_Y)

## On TMDb + IMDb Data

In [65]:
df_train.drop("id", axis=1, inplace=True)
df_test.drop("id", axis=1, inplace=True)

# x y split
train_X = df_train.ix[:,0:list(df_train.columns).index('Mystery')]
train_Y = df_train.ix[:,list(df_train.columns).index('Mystery'):len(df_train.columns)]

test_X = df_test.ix[:,0:list(df_test.columns).index('Mystery')]
test_Y = df_test.ix[:,list(df_test.columns).index('Mystery'):len(df_test.columns)]

# impute
def impute(dataf):
    for col in dataf.columns:
        dataf[col].fillna(dataf[col].mean(), inplace=True)

impute(train_X)
impute(train_Y)
impute(test_X)
impute(test_Y)

/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/chrischen/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [66]:
train_X.columns

Index([      u'budget',   u'popularity',       u'rating',      u'revenue',
            u'runtime', u'vote_average',   u'vote_count',        u'votes',
               u'year'],
      dtype='object')

In [68]:
params = {
    'n_estimators': [100],
    'max_features': ['auto', 'log2', None, 1, 3, 5, 7, 9],
    'n_jobs' : [-1]
}

CV_rf = GridSearchCV(RandomForestClassifier(), param_grid=params, cv=5, n_jobs=-1)
CV_rf.fit(train_X, train_Y)
print CV_rf.best_params_
print CV_rf.best_score_
print CV_rf.score(test_X, test_Y)

{'max_features': None, 'n_estimators': 100, 'n_jobs': -1}
0.0694993412385
0.0667251975417

In [70]:
hamming_loss(test_Y, CV_rf.predict(test_X))

0.12036874451273047

In [71]:
pd.DataFrame({'feature': train_X.columns, 'importance': CV_rf.best_estimator_.feature_importances_})

        feature  importance
0        budget    0.066487
1    popularity    0.155865
2        rating    0.114736
3       revenue    0.048941
4       runtime    0.153042
5  vote_average    0.096133
6    vote_count    0.106898
7         votes    0.125135
8          year    0.132764

# Classification By Movie Overview
Classification of movie genre using movie overviews from TMDB exclusively, using the text featurization methods of bigrams and Doc2vec.

In [64]:
from collections import namedtuple
import numpy as np
import pandas as pd
import timeit
from gensim.models import doc2vec
from gensim.parsing.preprocessing import stem
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import hamming_loss
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
import pickle
import string

# Identify Movies for which we have posters
We want to use the same movies for train, validation and test across all our classification tasks, so let's make sure the movies that we're using for text classification are the same ones we're using for image classification

In [31]:
from os import listdir

movie_names = []
for subdirectory in ['train', 'test', 'validation']:
    movie_names += listdir("data/posters_split/" + subdirectory)
movie_ids = [filename.split("-")[-1].split("_")[0] for filename in movie_names]
movie_ids = [int(id) for id in movie_ids]

# Text Preprocessing
We need to preprocess the movie overviews by stripping out punctuation and turning everything to lowercase. We deliberately choose to avoid stop word removal and stemming (both common NLP procedures) due to the relatively short length of the movie overviews. 

We also employ a 70/30 train-test split.

In [32]:
# Pandas has issues reading in a dataframe this large
# so read in chunk by chunk instead
full_dataset = pd.concat(pd.read_csv('data/full_raw_movie_overviews.csv', iterator=True, chunksize=1000), ignore_index=True)
print full_dataset.shape
full_dataset.head()

(31173, 23)

,movie_id,movie_title,overview,genre_id,War,Crime,Music,Comedy,History,Western,...,TV_Movie,Fantasy,Animation,Drama,Documentary,Science_Fiction,Horror,Action,Romance,Family
0,329865,Arrival,Taking place after alien crafts land around th...,"[53, 18, 878, 9648]",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,210577,Gone Girl,With his wife's disappearance having become th...,"[9648, 53, 18]",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,27205,Inception,"Cobb, a skilled thief who commits corporate es...","[28, 53, 878, 9648, 12]",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,158852,Tomorrowland,"Bound by a shared destiny, a bright, optimisti...","[28, 10751, 878, 12, 9648]",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,198663,The Maze Runner,"Set in a post-apocalyptic world, young Thomas ...","[28, 9648, 878, 53]",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [33]:
# Remove rows where overview is missing
full_dataset = full_dataset.dropna()
print full_dataset.shape

(20291, 23)

In [34]:
# Filter for movies that we have posters for, dropping duplicates
full_dataset = full_dataset[full_dataset['movie_id'].isin(movie_ids)].drop_duplicates()
print full_dataset.shape

(10509, 23)

In [35]:
# Convert to lowercase and remove punctuation
full_dataset['overview'] = full_dataset['overview'].str.lower()
full_dataset['overview'] = full_dataset['overview'].apply(lambda x: x.translate(string.maketrans(" "," "), string.punctuation))

In [39]:
# Use same test-train-validation split as posters
train_val_test_byid = pickle.load(open('data/train_val_test_byid.pkl', 'rb'))
train = full_dataset[full_dataset['movie_id'].isin(train_val_test_byid['train'])]
test = full_dataset[full_dataset['movie_id'].isin(train_val_test_byid['test'])]
validation = full_dataset[full_dataset['movie_id'].isin(train_val_test_byid['validation'])]
print train.shape, test.shape, validation.shape

(8405, 23) (1049, 23) (1055, 23)

# Bigram feature generation

In [40]:
count_vectorizer = CountVectorizer(ngram_range=(1,2))
count_vectorizer.fit(train["overview"])

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [41]:
# Generate bigram features
train_bigrams = count_vectorizer.transform(train["overview"])
val_bigrams = count_vectorizer.transform(validation["overview"])

# Doc2vec feature generation
We use doc2vec to learn fixed length vector representations of each of the documents (movie overviews) and therefore avoid time intensive route of manual feature engineering.

In [42]:
taggedXML = namedtuple('TaggedXML', 'words tags')
documents = []

for i in train.index:
    tags = [train['movie_id'][i]]
    documents.append(taggedXML(train['overview'][i].split(), tags))

In [45]:
d2v = doc2vec.Doc2Vec(documents, size=100, workers=4, iter=30)
# Save model
d2v.save("d2v_models/d2v_size100_iter30")

In [46]:
# Use trained d2v model in order to infer feature vectors for each of the documents
train_d2v_features = [d2v.infer_vector(document) for document in train["overview"]]
val_d2v_features = [d2v.infer_vector(document) for document in validation["overview"]]

# Multilabel Random Forest Classification

In [53]:
# Get labels into multilabel classification format for train and test
train_y = train.ix[:, 'War':]
val_y = validation.ix[:, 'War':]

In [56]:
# Train random forest on bigram features
bigram_rf = RandomForestClassifier(n_estimators=10)
bigram_rf.fit(train_bigrams, train_y)

train_bigram_pred = bigram_rf.predict(train_bigrams)
val_bigram_pred = bigram_rf.predict(val_bigrams)

bigram_rf.score(val_bigrams, val_y)

0.023696682464454975

In [81]:
print "Hamming loss on train with bigram features:", hamming_loss(train_y, train_bigram_pred)
print "Hamming loss on validation with bigram features:", hamming_loss(val_y, val_bigram_pred)

Hamming loss on train with bigram features: 0.0176023043927
Hamming loss on validation with bigram features: 0.134696931903

In [58]:
# Train random forest on doc2vec features
d2v_rf = RandomForestClassifier(n_estimators=10)
d2v_rf.fit(train_d2v_features, train_y)

train_d2v_pred = d2v_rf.predict(train_d2v_features)
val_d2v_pred = d2v_rf.predict(val_d2v_features)

d2v_rf.score(val_d2v_features, val_y)

0.0056872037914691941

In [82]:
print "Hamming loss on train with d2v features:",  hamming_loss(train_y, train_d2v_pred)
print "Hamming loss on validation with d2v features:", hamming_loss(val_y, val_d2v_pred)

Hamming loss on train with d2v features: 0.0214095619775
Hamming loss on validation with d2v features: 0.141032676478

# Naive 0 Classifier (Baseline)

In [83]:
print "Hamming loss on train with naive all 0 classifier:",  hamming_loss(train_y, np.zeros((train_d2v_pred.shape)))
print "Hamming loss on validation with naive all 0 classifier:",  hamming_loss(val_y, np.zeros((val_d2v_pred.shape)))

Hamming loss on train with naive all 0 classifier: 0.14239644322
Hamming loss on validation with naive all 0 classifier: 0.139835370417

# Naive Bayes on Bigram Features, One v. Rest Classifier for Multilabels

In [65]:
# Train random forest on bigram features
nb = OneVsRestClassifier(MultinomialNB())
nb.fit(train_bigrams, train_y)

train_nb_pred = nb.predict(train_bigrams)
val_nb_pred = nb.predict(val_bigrams)

nb.score(val_bigrams, val_y)

0.016113744075829384

In [84]:
print "Hamming loss on train with naive bayes:",  hamming_loss(train_y, train_nb_pred)
print "Hamming loss on validation with naive bayes:", hamming_loss(val_y, val_nb_pred)

Hamming loss on train with naive bayes: 0.020470271455
Hamming loss on validation with naive bayes: 0.128261411823

In [80]:
# Check the datapoints for which the naive bayes predictions match the actual 
# multilabels in the validation set
val_y[(val_y == val_nb_pred).all(axis=1)]

,War,Crime,Music,Comedy,History,Western,Thriller,Mystery,Adventure,TV_Movie,Fantasy,Animation,Drama,Documentary,Science_Fiction,Horror,Action,Romance,Family
6726,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
7711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8054,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8219,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
8306,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
26891,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27489,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27574,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27645,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27728,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27741,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27831,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
27895,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
30554,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

Unfortunately from the abysmal performance in terms of both Hamming loss and subset accuracy, it does not look like predicting by movie overview alone is a feasible approach for this multilabel classification problem.